# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('projector', models.BooleanField()),
                ('board', models.BooleanField()),
                ('computers', models.PositiveSmallIntegerField()),
                ('info', models.TextField(max_length=3000)),
                ('seats', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
