# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160415_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='dergee',
            new_name='degree',
        ),
    ]
