# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='dzien_wydzialu/home/static/images'),
        ),
    ]
