# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160527_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
