# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160601_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroup',
            name='assigned_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
        ),
    ]
