# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_visitorgroup_assigned_group'),
        ('home', '0015_image_name'),
    ]

    operations = [
    ]
