# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorgroup',
            name='assigned_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
        ),
    ]
