# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='lecturer',
            new_name='lecturers',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
